### ISSUE TITLE
Quitting application after clicking on Install still installs the packages in background

### ISSUE THREAD

**Issue by anupam-git** [nomad-desktop/nx-software-updater#5]
The Helper process is not getting terminated when the application is closed explicitly.

Hence if `Install` Button is clicked and before completion of the `Download and Install` process, the application is closed explictly, the `Download and Install` process by the helper is still carried on in the background.

**Comment by UriHerrera** [comment]
Have the application sent to the system tray if the user were to click on close so that it runs on the background and performs the update process. Once that's done send a notification to the user.

**Comment by anupam-git** [comment]
Implemented Functionality for System Tray

**Comment by anupam-git** [comment]
This issue was moved to anupam-git/nx-software-updater#7
