### ISSUE TITLE
Use Qt Quick Controls 2 for UI 

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nx-software-updater#8]
Currently the KCM looks like this:
![](https://i.imgur.com/bcGsIWO.png)
![](https://i.imgur.com/5HIfb6G.png)

It doesn't respect what theme is used it uses hardcoded colors. Notice too that the buttons are of a different width and height when compared to System Settings' buttons.

**Comment by anupam-git** [comment]
This issue was moved to anupam-git/nx-software-updater#10
